# Generated by Django 5.1.5 on 2025-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='practicenote',
            name='exercises_completed',
            field=models.TextField(blank=True, help_text='List exercises you completed', null=True),
        ),
        migrations.AddField(
            model_name='practicenote',
            name='gym_days_per_week',
            field=models.IntegerField(blank=True, help_text='How many days per week do you plan to train?', null=True),
        ),
        migrations.AddField(
            model_name='practicenote',
            name='session_rating',
            field=models.IntegerField(blank=True, help_text='Rate your session 1-5', null=True),
        ),
        migrations.AddField(
            model_name='practicenote',
            name='weekly_split',
            field=models.CharField(blank=True, choices=[('3day_full', '3-Day Full Body'), ('4day_upper_lower', '4-Day Upper/Lower'), ('5day_ppl', '5-Day Push/Pull/Legs'), ('custom', 'Custom Split')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='practicenote',
            name='what_to_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicenote',
            name='what_went_well',
            field=models.TextField(blank=True, null=True),
        ),
    ]
